# Plan of Attack 3 - Ejercicios basicos
Ejercicios del plan de ataque. No son del tutorial ni del libro. 

Importar librerías

In [8]:
import math as mt
mt.sqrt(25)

5.0

In [9]:
mt.pi

3.141592653589793

In [11]:
from numpy import random
import numpy as np
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.23907533, 0.68185595, 0.6111295 , 0.63969012, 0.39998673],
       [0.8953188 , 0.86285982, 0.22380233, 0.25103992, 0.06593243],
       [0.22505548, 0.3189059 , 0.09266634, 0.42654686, 0.71977682],
       [0.93087423, 0.95960475, 0.13100169, 0.91672347, 0.47311047],
       [0.2563223 , 0.62725968, 0.58700301, 0.43549124, 0.77401138]])

In [13]:
dataOne = random.rand(5,5)
np.mean(dataOne)

0.5691870017079098

In [18]:
var1 = 'I love Saprissa'
var2 = 25
var3 = 25.0
print(var1)
print(var2)
print(var3)

I love Saprissa
25
25.0


In [17]:
type(var1)

str

In [19]:
type(var2)

int

In [20]:
type(var3)

float

In [24]:
var4 = var2+var3
var5 = " & DataScience"
var6 = var1 + var5
print(var4)
print(var6)

50.0
I love Saprissa & DataScience


In [25]:
var7=var6 + str(var4)
print(var7)

I love Saprissa & DataScience50.0


In [26]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


No entiendo el tema de los rangos. Si yo pongo [0:1] debería dar dos valores: el que está en la posición 0 hasta el que está en la posición 1. Sin embargo solo da 1 valor. Esto debo revisarlo más a fondo. 

In [30]:
print(listOne[1:2])

[2]


In [31]:
print(dataOne)

[[0.41532501 0.99090505 0.14276702 0.59185023 0.96278424]
 [0.70721062 0.73164229 0.80788108 0.75442264 0.77604608]
 [0.58747361 0.22226429 0.81013122 0.04512378 0.77270865]
 [0.03706679 0.56396342 0.07867603 0.1721303  0.57470795]
 [0.15561413 0.98197546 0.63175041 0.74590829 0.96934645]]


In [33]:
print(dataOne[0])

[0.41532501 0.99090505 0.14276702 0.59185023 0.96278424]


In [34]:
print(dataOne[0:1])

[[0.41532501 0.99090505 0.14276702 0.59185023 0.96278424]]


In [35]:
print(dataOne[0:2])

[[0.41532501 0.99090505 0.14276702 0.59185023 0.96278424]
 [0.70721062 0.73164229 0.80788108 0.75442264 0.77604608]]


In [36]:
print(dataOne[0][0])

0.41532500723505783


In [37]:
print(dataOne[0][0:1])

[0.41532501]


In [38]:
print(dataOne[0][0:2])

[0.41532501 0.99090505]


In [39]:
print(dataOne[0][1:3])

[0.99090505 0.14276702]


In [40]:
tel = {'jack': 4098, 'sape': 4139}

In [43]:
print(tel['jack'])

4098


In [44]:
var8 = tel['jack']+tel['sape']
print(var8)

8237


In [47]:
print(mt.gcd(tel['jack'],tel['sape']))

1
